Multiplatform venv
aws/aws-encryption-sdk-cli pull request #233
Opened 2021-10-29 08:22 UTC by phasenoisepon

*Issue #, if available:* closes #232

*Description of changes:*
- Adds setup instructions for setting up the tool in a python virtual environment in README.rst
- Adds github workflow yaml for Venv specifc testing on MacOS/Linux/Windows environments

Comments:
- Windows specific sourcing has to be done to test Windows/Powershell instructions in the readme
- Not the happiest with the duplication of code in the workflow, might be able to split the detection into each run step, but then you would have to deal with PowerShell / Bash incompatibility [(default shell docs)](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell)
- PR'ed for Hacktoberfest (so if this passes muster I'd appreciate it being tagged with `hacktoberfest-accepted`)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2021-10-29 19:28 UTC, phasenoisepon commented on README.rst
> +      (env) > pip install aws-encryption-sdk-cli
On a vanilla windows powershell install, activating the virtual environment by sourcing the venv will add the venv's name to your shell.

2021-10-29 20:51 UTC, phasenoisepon commented on .github/workflows/install.yaml
> +          pip install --upgrade -r ci-requirements.txt
resolved this in https://github.com/aws/aws-encryption-sdk-cli/pull/233/commits/1f036ccc205c42ac3ba7a1260e20d9bbfcc9757c

The venv setup step should install the package from pip, but inside of the venv (hence activating the venv). Or do you want the venv to be activated and installed into in the `test` step?

2021-10-29 21:29 UTC, texastony commented on README.rst
> +      (env) > pip install aws-encryption-sdk-cli
Groovy. Thanks!

2021-10-29 21:36 UTC, texastony commented
@phasenoisepon I may have led you astray... I thought that the environmental variables for using the AWS KMS keys were already configured... but they clearly are not there. 

I think I will need to look into I can do for a local test that encrypts and decrypts without calling KMS, or ensuring that the environmental variables are set up correctly.

Sorry for leading you astray.

2021-11-02 14:14 UTC, texastony requested changes
I thought about it, and came to the conclusion that ensuring the library is installed can just be done via the `get version` flag. 

I am so sorry that I lead you astray earlier. I fell for the oldest trick: it works on my machine, so it will work on all machines. 

Ironically, that is exactly what your PR is preventing. By ensuring the install instructions are tested, we ensure that this works on all supported machines.
Thanks again for this.

2021-11-02 14:14 UTC, texastony commented on .github/workflows/install.yaml
> +          python3 -c "assert '$PLAINTEXT' == '$INPUT_TEXT'"
suggestion: Let's leave the encryption testing to the CI actions in AWS CodeBuild
Let us just ensure that the library is installed by checking that the version command returns. 
```suggestion
    aws-encryption-cli --version
```

2021-11-02 14:14 UTC, texastony commented on .github/workflows/install.yaml
> +          python3 -c "assert '$PLAINTEXT' == '$INPUT_TEXT'"
suggestion: Let's leave the encryption testing to the CI actions in AWS CodeBuild
Let us just ensure that the library is installed by checking that the version command returns.
```suggestion
          aws-encryption-cli --version
```

2021-11-02 23:47 UTC, phasenoisepon commented
@texastony when you're in office, approve the other workflows.

latest commits should give this the functionality you were looking for.

2021-11-09 22:15 UTC, texastony approved these changes

2021-11-09 22:17 UTC, merged