feat: Mark ESDK-CLI-1.x as EOS
aws/aws-encryption-sdk-cli pull request #308
Opened 2022-08-02 21:17 UTC by texastony

*Issue #, if available:* Mark the ESDK-CLI-1.x as End of Support

*Description of changes:*
- Issues a log warning that this version is no longer supported.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-08-02 22:11 UTC, texastony commented
On my local, using Python 3.5.10 (as GHA is using), `tox -e flake8` is failing to execute.
From the logs on GHA, it looks like it is failing to execute there as well.
I think there may be an issue with flake8 and Python 3.5.10.
flake8 passes when run with Python 3.10.0.

2022-08-03 15:18 UTC, smswz commented
I would not bother testing anything prior to 3.7. Both 3.5 and 3.6 are EOL. I'm sure flake8 no longer supports those versions

2022-08-03 15:21 UTC, smswz requested changes

2022-08-03 15:21 UTC, smswz commented on src/aws_encryption_sdk_cli/compatability.py
> +    minimum_version = (3, 6)
This should probably be bumped. 3.7 is the oldest maintained Python version.

https://peps.python.org/pep-0494/

2022-08-26 01:59 UTC, closed without merging